version: '3.8'

services:
  rest:
    build: ./servidor/rest
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data

  graphql:
    build: ./servidor/graphql
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/data

  grpc:
    build: ./servidor/grpc
    ports:
      - "50051:50051"
    volumes:
      - ./data:/app/data

  soap:
    build: ./servidor/soap
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

volumes:
  data: 