# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livro.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'livro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blivro.proto\x12\x05livro\"O\n\x05Livro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\x12\x0e\n\x06genero\x18\x05 \x01(\t\"\x07\n\x05Vazio\"\x1c\n\x08Resposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t2m\n\x0cLivroService\x12/\n\x0e\x41\x64icionarLivro\x12\x0c.livro.Livro\x1a\x0f.livro.Resposta\x12,\n\x0cListarLivros\x12\x0c.livro.Vazio\x1a\x0c.livro.Livro0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIVRO']._serialized_start=22
  _globals['_LIVRO']._serialized_end=101
  _globals['_VAZIO']._serialized_start=103
  _globals['_VAZIO']._serialized_end=110
  _globals['_RESPOSTA']._serialized_start=112
  _globals['_RESPOSTA']._serialized_end=140
  _globals['_LIVROSERVICE']._serialized_start=142
  _globals['_LIVROSERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
